/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SVM_J2C */

#ifndef _Included_SVM_J2C
#define _Included_SVM_J2C
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SVM_J2C
 * Method:    do_cross_validation
 * Signature: (IIIIDDDDDI[I[DDDIII)V
 */
JNIEXPORT void JNICALL Java_SVM_1J2C_do_1cross_1validation
  (JNIEnv *, jobject, jint, jint, jint, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jint, jintArray, jdoubleArray, jdouble, jdouble, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
